sudo: required
services:
  - docker

before_install:
  - docker build -t jorgebee/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jorgebee/docker-react npm run test -- --watchAll=false --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "jorge-docker-react"
  env: "JorgeDockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-048772738432"
  bucket_path: "jorge-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"